Needs["ClassicalLieAlgebra`"];
VerificationTest[ HighestWeight[Irrep[SU[3], {1, 1}]], {1, 1}, TestID->"hw" ];
VerificationTest[ Head[Irrep[SU[3], {1, 1}]], Irrep, TestID->"irrep-inert" ];
VerificationTest[ Irrep[SU[3], {1, 1, 0}], $Failed, {Irrep::badweight}, TestID->"wrong-length" ];
VerificationTest[ Irrep[SU[3], {1, -1}], $Failed, {Irrep::badweight}, TestID->"negative-label" ];
VerificationTest[ Irrep[SO[5], {0, 1}], Irrep[LieAlgebra["B", 2], {0, 1}], TestID->"sugar-canonicalizes" ];
VerificationTest[ RepresentationDimension[Irrep[SU[3], {1, 0}]], 3, TestID->"dim-su3-fund" ];
VerificationTest[ RepresentationDimension[Irrep[SU[3], {1, 1}]], 8, TestID->"dim-su3-adjoint" ];
VerificationTest[ RepresentationDimension[Irrep[SO[5], {1, 0}]], 5, TestID->"dim-so5-vector" ];
VerificationTest[ RepresentationDimension[Irrep[SO[5], {0, 1}]], 4, TestID->"dim-so5-spinor" ];
VerificationTest[ RepresentationDimension[Irrep[Sp[4], {1, 0}]], 4, TestID->"dim-sp4-defining" ];
VerificationTest[ RepresentationDimension[Irrep[Sp[4], {0, 1}]], 5, TestID->"dim-sp4-omega2" ];
VerificationTest[ RepresentationDimension[Irrep[SU[4], {0, 0, 0}]], 1, TestID->"dim-trivial" ];
VerificationTest[ RepresentationDimension[Irrep[SO[7], {0, 0, 1}]], 8, TestID->"dim-so7-spinor" ];
